### ISSUE TITLE
Error "Invalid type in function 'share' in base 'JNISingleton'" on Godot 4.4beta3

### ISSUE THREAD

**Issue by etherealxx** [cengiz-pz/godot-android-share-plugin#9]
I tested the addon with my project on Godot 4.3.stable, it works. It does not work on 4.4.beta3.

```
Invalid type in function 'share' in base 'JNISingleton'. Cannot convert argument 1 from Dictionary to Object.
```
![Image](https://github.com/user-attachments/assets/fa9f7b25-7a77-49ea-af89-6b6b1245bd84)

maybe investigate it to find the issue then report to godot

also the share node has no icon in 4.4.beta3

![Image](https://github.com/user-attachments/assets/6a450f52-402f-4e3b-a16c-a27b866cb96c)

the ios addon works fine in 4.4.beta3

**Comment by syntaxerror247** [comment]
Try export template from this PR artifect https://github.com/godotengine/godot/pull/103733/checks. This issue is a regression and this PR should fix it.

**Comment by etherealxx** [comment]
the PR did fixed it yeah

<img src="https://github.com/user-attachments/assets/2e8e0d30-3b58-4733-9cd5-9a28cd54f72d" width="200"/>

**Comment by KeyVux** [comment]
I compiled Godot with commit [f52b2e4](https://github.com/godotengine/godot/commit/f52b2e4db4d785e5f03377de7140808ba99f0f95)  but the error still exists. My compiled godot says `v4.5.dev.custom_build [f52b2e4db]`. It did not have Android Build Template so I copied from 4.4.stable to 4.5.dev then install it.

Is there something I missed?

**Comment by sebageek** [comment]
Godot 4.4.1-rc1 [has been released](https://godotengine.org/article/release-candidate-godot-4-4-1-rc-1/) ([download](https://godotengine.org/download/archive/4.4.1-rc1/)) and included the PR linked by @syntaxerror247. With this, sharing on Android works again for me.

**Comment by ducviet321** [comment]
> [@KeyVux](https://github.com/KeyVux) you're doing it wrong. Either wait for 4.4.1-rc1 to release in a few days or you need to build the android template by yourself

Are there instruction to build Android template on my own? Thanks

**Comment by etherealxx** [comment]
@ducviet321 here: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html#building-the-export-templates

**Comment by sebageek** [comment]
@ducviet321 in case you don't want to build your own: everything worked out of the box for me with 4.4.1-rc1, even the template download just let me install it via the editor. So no manual building necessary, expect you really want to do it.
